---
version: 2
updates:
  - package-ecosystem: pip
    directory: "/AWS"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/Azure"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
